#!/usr/bin/env node

// Changelog generator: collects `done` entries from docs/TASKS.md since the
// last release and prepends a release section to CHANGELOG.md.
// Preview by default; pass --yes to write.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CHANGELOG_HEADER = '# Changelog\n\nGenerated by tools/release/release.mjs from docs/TASKS.md.\n';
const RELEASE_HEADING_PATTERN = /^## \[(\d+\.\d+\.\d+)\] — (\d{4}-\d{2}-\d{2})/m;

function parseArgs(argv) {
  const args = {};
  for (let index = 0; index < argv.length; index += 1) {
    const token = argv[index];
    if (!token.startsWith('--')) continue;

    const key = token.slice(2);
    const next = argv[index + 1];
    if (!next || next.startsWith('--')) {
      args[key] = true;
      continue;
    }

    args[key] = next;
    index += 1;
  }

  return args;
}

function parseField(block, label) {
  const pattern = new RegExp(`^\\*\\*${label}:\\*\\*\\s*(.*)$`, 'm');
  const match = block.match(pattern);
  return match ? match[1].trim() : '';
}

function parseDoneEntries(tasksContent, sinceDate) {
  const entries = [];
  const headingPattern = /^### (\d{4}-\d{2}-\d{2}) — ([^—]+) — (.+)$/gm;
  const headings = [...tasksContent.matchAll(headingPattern)];

  for (let index = 0; index < headings.length; index += 1) {
    const [, date, agent, area] = headings[index];
    if (sinceDate && date <= sinceDate) continue;

    const bodyEnd = index + 1 < headings.length ? headings[index + 1].index : tasksContent.length;
    const block = tasksContent.slice(headings[index].index, bodyEnd);
    if (parseField(block, 'Status') !== 'done') continue;

    entries.push({ date, agent: agent.trim(), area: area.trim(), did: parseField(block, 'Did') });
  }

  return entries.sort((a, b) => a.date.localeCompare(b.date));
}

function lastReleaseDate(changelogContent) {
  const match = changelogContent.match(RELEASE_HEADING_PATTERN);
  return match ? match[2] : null;
}

function buildReleaseSection(version, date, entries) {
  const lines = [`## [${version}] — ${date}`, ''];
  if (!entries.length) {
    lines.push('_No completed TASKS.md entries since the last release._');
  } else {
    for (const entry of entries) {
      lines.push(`- **${entry.area}** (${entry.agent}): ${entry.did}`);
    }
  }
  return lines.join('\n');
}

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (args.help) {
    console.log('Usage: node release.mjs --version <x.y.z> [--repo-root <path>] [--date YYYY-MM-DD] [--yes]');
    console.log('Previews the changelog entry by default; --yes writes it.');
    return;
  }

  const version = typeof args.version === 'string' ? args.version : '';
  if (!/^\d+\.\d+\.\d+$/.test(version)) {
    throw new Error('--version is required and must be x.y.z (see docs/RELEASES.md)');
  }

  const repoRoot = args['repo-root'] ? resolve(args['repo-root']) : resolve(__dirname, '..', '..');
  const tasksPath = join(repoRoot, 'docs', 'TASKS.md');
  const changelogPath = join(repoRoot, 'CHANGELOG.md');
  if (!existsSync(tasksPath)) {
    throw new Error(`Missing required file: ${tasksPath}`);
  }

  const changelog = existsSync(changelogPath) ? readFileSync(changelogPath, 'utf8') : CHANGELOG_HEADER;
  const since = lastReleaseDate(changelog);
  const date = typeof args.date === 'string' ? args.date : new Date().toISOString().slice(0, 10);
  const entries = parseDoneEntries(readFileSync(tasksPath, 'utf8'), since);
  const section = buildReleaseSection(version, date, entries);

  console.log(`Release ${version} (${date}), entries since ${since ?? 'beginning'}:\n`);
  console.log(section);

  if (!args.yes) {
    console.log('\nPreview complete. Re-run with --yes to write CHANGELOG.md.');
    return;
  }

  if (changelog.includes(`## [${version}]`)) {
    throw new Error(`CHANGELOG.md already contains a [${version}] section.`);
  }

  const headerEnd = changelog.indexOf('\n## [');
  const updated = headerEnd === -1
    ? `${changelog.trimEnd()}\n\n${section}\n`
    : `${changelog.slice(0, headerEnd + 1)}${section}\n\n${changelog.slice(headerEnd + 1)}`;
  writeFileSync(changelogPath, updated.replace(/\r\n/g, '\n'));
  console.log(`\nUpdated: ${changelogPath}`);
}

try {
  main();
} catch (error) {
  console.error(`[error] ${error.message}`);
  process.exit(1);
}
